# Generated by Django 4.1.1 on 2023-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_options_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to_do',
            field=models.TimeField(),
        ),
    ]
