# Generated by Django 4.1.1 on 2023-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_options_alter_task_time_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_to_do',
            field=models.DateTimeField(),
        ),
    ]
