# Generated by Django 4.1.1 on 2023-07-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_time_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Important', 'important'), ('Urgent', 'urgent'), ('Not Important', 'not important')], default='Not Important', max_length=50),
        ),
    ]
