# Generated by Django 4.1.1 on 2023-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Not Important', 'Not Important')], default='Not Important', max_length=50),
        ),
    ]
